class RustRingZModN:
    def __init__(self, n: int) -> None: ...
    def add(self, a: int, b: int) -> int: ...
    def sub(self, a: int, b: int) -> int: ...
    def mul(self, a: int, b: int) -> int: ...
    def is_zero(self, a: int) -> bool: ...
    def gcd(self, a: int, b: int) -> int: ...
    def ass(self, a: int) -> int: ...
    def ann(self, a: int) -> int: ...
    def rem(self, a: int, b: int) -> int: ...
    def quo(self, a: int, b: int) -> int: ...
    def div(self, a: int, b: int) -> int: ...
    def unit(self, a: int) -> int: ...
    def gcdex(self, a: int, b: int) -> tuple[int, int, int, int, int]: ...
    def stab(self, a: int, b: int, c: int) -> int: ...

import numpy as np
from numpy.typing import NDArray

def rust_smith_from_diagonal(
    diag_data: NDArray[np.int64],
    modulus: int,
) -> tuple[NDArray[np.int64], NDArray[np.int64], NDArray[np.int64]]: ...

def rust_merge_smith_blocks(
    a_data: NDArray[np.int64],
    b_data: NDArray[np.int64],
    modulus: int,
) -> tuple[NDArray[np.int64], NDArray[np.int64], NDArray[np.int64]]: ...
