"""Modular arithmetic helpers for Z/NZ used across Smith normal form.

Provides the ``RingZModN`` abstraction with arithmetic, ideal, and gcd tools
needed by the Smith normal form algorithms implemented in this package.

When the Rust extension is available, hot-path methods delegate to the native
implementation for speed. The pure-Python implementation remains available as
the reference path and as a fallback when the extension cannot be imported.
"""

import math
from numbers import Integral

try:
    from modularsnf._rust import RustRingZModN as _RustRing
except ImportError:
    _RustRing = None  # type: ignore[assignment]

INT64_MIN = -(1 << 63)
INT64_MAX = (1 << 63) - 1


def _coerce_int64(name: str, value: object) -> int:
    """Return *value* as a signed 64-bit integer or raise."""
    if isinstance(value, bool) or not isinstance(value, Integral):
        raise TypeError(f"{name} must be an integer")

    int_value = int(value)
    if int_value < INT64_MIN or int_value > INT64_MAX:
        raise OverflowError(f"{name} must fit in a signed 64-bit integer")
    return int_value


class RingZModN:
    """
    Represents Z/NZ. Implements ALL basic operations defined in
    Storjohann's Dissertation Section 1.1.
    """

    N: int

    def __init__(self, N: int) -> None:
        int_modulus = _coerce_int64("modulus", N)
        if int_modulus < 2:
            raise ValueError("Modulus N must be >= 2")
        self.N = int_modulus
        self._rust = _RustRing(int_modulus) if _RustRing is not None else None

    def add(self, a: int, b: int) -> int:
        return (a + b) % self.N

    def sub(self, a: int, b: int) -> int:
        return (a - b) % self.N

    def mul(self, a: int, b: int) -> int:
        return (a * b) % self.N

    def is_zero(self, a: int) -> bool:
        return (a % self.N) == 0

    def gcd(self, a: int, b: int) -> int:
        """Principal generator of the ideal (a, b) in Z/NZ."""
        if self._rust is not None:
            return self._rust.gcd(a, b)
        return math.gcd(a % self.N, math.gcd(b % self.N, self.N))

    def rem(self, a: int, b: int) -> int:
        """
        Return the prescribed residue of a with respect to Ass(b).
        In Z, this is typically a % b, but we must respect the ring structure.
        Ref: Def 1.4 consistent with Z.
        """
        b_ass = self.ass(b)
        if b_ass == 0:
            return a % self.N
        return (a % self.N) % b_ass

    def quo(self, a: int, b: int) -> int:
        """
        Return q such that a - qb = rem(a, b).
        """
        r = self.rem(a, b)
        diff = self.sub(a, r)
        # Find q such that q*b equals diff; diff is a multiple of b by definition of the remainder.
        return self.div(diff, b)

    def ann(self, a: int) -> int:
        """
        Return generator of the annihilator ideal {x | xa = 0}.
        In Z/N, Ann(a) is generated by N / gcd(a, N).
        """
        g = math.gcd(a % self.N, self.N)
        return (self.N // g) % self.N

    def gcdex(self, a: int, b: int) -> tuple[int, int, int, int, int]:
        """
        Returns (g, s, t, u, v) such that:
        [s t] [a] = [g]
        [u v] [b]   [0]
        and sv - tu = unit.
        """
        if self._rust is not None:
            return self._rust.gcdex(a, b)
        a_val = a % self.N
        b_val = b % self.N

        # Return the specialized form when b is a multiple of a in Z/N.
        if a_val != 0 and (b_val % math.gcd(a_val, self.N) == 0):
            # Check if exact division exists
            try:
                q = self.div(b_val, a_val)
                # s=1, t=0, u=-q, v=1 -> det = 1
                return (a_val, 1, 0, (self.N - q) % self.N, 1)
            except ValueError:
                pass  # Fall through to standard logic if exact division fails.

        # Standard Euclidean
        r0, r1 = a_val, b_val
        s0, s1 = 1, 0
        t0, t1 = 0, 1

        while r1 != 0:
            q = r0 // r1
            r0, r1 = r1, r0 - q * r1
            s0, s1 = s1, s0 - q * s1
            t0, t1 = t1, t0 - q * t1

        g, s, t = r0, s0, t0

        # Compute u, v such that u*a + v*b = 0 and det is a unit (u = -b/g, v = a/g).
        if g == 0:
            return 0, 1, 0, 0, 1

        u = -(b_val // g)
        v = a_val // g

        return (g % self.N, s % self.N, t % self.N, u % self.N, v % self.N)

    def div(self, a: int, b: int) -> int:
        """Exact division a/b. Raises error if b does not divide a."""
        if self._rust is not None:
            return self._rust.div(a, b)
        a_val, b_val = a % self.N, b % self.N
        g, x, _ = self._egcd(b_val, self.N)
        if a_val % g != 0:
            raise ValueError(f"{a} not divisible by {b} in Z/{self.N}")
        return (x * (a_val // g)) % (self.N // g)

    def stab(self, a: int, b: int, c: int) -> int:
        if self._rust is not None:
            return self._rust.stab(a, b, c)
        a, b, c = a % self.N, b % self.N, c % self.N
        target = self.gcd(a, self.gcd(b, c))
        for x in range(self.N):
            candidate = (a + x * b) % self.N
            current = self.gcd(candidate, c)  # = gcd(a + x b, c, N)
            if current == target:
                return x
        raise ValueError(f"Stab failed for a={a}, b={b}, c={c} in Z/{self.N}")

    def ass(self, a: int) -> int:
        """Associate: gcd(a, N)."""
        return math.gcd(a % self.N, self.N)

    def unit(self, a: int) -> int:
        """Return u such that u*a = Ass(a)."""
        a_val = a % self.N
        g, u, _ = self._egcd(a_val, self.N)
        return u % self.N

    def _egcd(self, a: int, b: int) -> tuple[int, int, int]:
        r0, r1, s0, s1 = a, b, 1, 0
        while r1:
            q = r0 // r1
            r0, r1 = r1, r0 - q * r1
            s0, s1 = s1, s0 - q * s1
        return r0, s0, 0  # t not needed here
